title: Project

files:
  sortable: true

pages: true
  template: project

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4

  intro:
    label: Intro
    type:  textarea

  text:
    label: Text
    type:  textarea

  videolink:
    label: Video
    type:  text
