title: Project

files:
  sortable: true

pages: true
  template: project

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  created:
    label: Datum
    type:  date
    width: 1/4
    default: today

  intro:
    label: Intro
    type:  textarea

  text:
    label: Text
    type:  textarea

  showslider:
    label: ImageSlider
    type: checkbox
    text: show Images as slider
    width: 1/4

  videolink:
    label: Video
    type:  text
    width: 3/4